name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install bun (development only)
        if: matrix.platform == 'ubuntu-20.04' || matrix.platform == 'macos-latest'
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build and upload a GitHub release
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: |
            See the assets to download and install this version.

            If you get a virus warning read this article: https://tauri.by.simon.hyll.nu/concepts/security/false_positives/.

            Mac: Extract the .app from the .dmg and run `xattr -d com.apple.quarantine your-app.app`.
            Windows: Run `attrib -r your-app.msi:Zone.Identifier`.
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
